### ISSUE TITLE
Not work with freeswitch 1.10.12

### ISSUE THREAD

**Issue by Austin-Yu-OneBox** [freeswitch/mod_unimrcp#16]
freeswitch@Austin> load mod_unimrcp.dll
2024-09-11 17:32:48.625711 97.96% [INFO] switch_stun.c:915 External ip address detected using STUN: 103.231.84.235
2024-09-11 17:32:48.865775 97.96% [INFO] switch_stun.c:915 External ip address detected using STUN: 103.231.84.237
2024-09-11 17:32:48.915871 97.96% [INFO] mod_enum.c:884 ENUM Reloaded
2024-09-11 17:32:48.915871 97.96% [INFO] switch_time.c:1436 Timezone reloaded 597 definitions

+OK Reloading XML
-ERR [module load file routine returned an error]

2024-09-11 17:32:48.915871 97.96% [CRIT] switch_loadable_module.c:1754 Error Loading module C:/Program Files/FreeSWITCH/mod/mod_unimrcp.dll
**dll open error [126l]
**
